spring:
  application:
    name: listify

  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${spotify.client-id}
            client-secret: ${spotify.client-secret}
            provider: spotify
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/spotify"
            scope:
              - user-read-private
              - user-read-email
            client-name: Spotify

        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id

spotify:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  redirect-uri: ${REDIRECT_URI}
