spring:
  application:
    name: listify

  config:
    import: optional:.env[.properties]

  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${SPOTIFY_REDIRECT_URI}
            scope:
              - user-read-private
              - user-read-email
            client-name: Spotify

        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id

server:
  port: 9090

spotify:
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}
  redirect-uri: ${SPOTIFY_REDIRECT_URI}